name: Build

on:
  push:
    branches: [ master ]
    
jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: |
        make
    - uses: actions/upload-artifact@v2
      with:
        name: gmodws
        path: compiled/gmodws
